name = "Diego"
license = "MIT"
licenselink = "https://github.com/Hjdskes/diego-hugo-theme/blob/master/LICENSE.md"
description = "A clean, fast and responsive theme"
homepage = "https://github.com/Hjdskes/diego-hugo-theme"
tags = ["clean", "fast", "small", "minimal", "responsive", "typography"]
features = ["flexible", "fast", "minimal", "small"]

[author]
    name = "Jente Hidskes"
    homepage = "https://www.hjdskes.nl"

[original]
    name = "Diego Vicente"
    homepage = "diegovicente.gitlab.io"
    repo = "https://gitlab.com/diegovicente"
