name = "Diego"
license = "MIT"
licenselink = "https://github.com/Hjdskes/diego-hugo-theme/blob/master/LICENSE.md"
description = "A clean, fast and responsive theme"
homepage = "https://github.com/Hjdskes/diego-hugo-theme"
tags = ["clean", "fast", "small", "minimal", "responsive", "typography"]
features = ["flexible", "fast", "minimal", "small"]
# TODO: update once done
min_version = 0.20.2

[author]
    name = "Jente Hidskes"
    homepage = "https://hjdskes.nl"

[original]
    name = "Diego Vicente"
    homepage = "diegovicente.gitlab.io"
    repo = "https://gitlab.com/diegovicente"
